#!/bin/bash
# Hello World Script

NAME="${1:-World}"
LANG="${2:-en}"

case "$LANG" in
  zh)
    echo "你好，$NAME！"
    ;;
  es)
    echo "¡Hola, $NAME!"
    ;;
  *)
    echo "Hello, $NAME!"
    ;;
esac

echo ""
echo "Output generated by custom skill at $(date)"
